# Generated by Django 5.1.3 on 2024-11-11 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_donor_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('default_donor_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('default_donor_email_address', models.EmailField(blank=True, max_length=100, null=True)),
                ('default_donor_postcode', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
