# Generated by Django 5.1.3 on 2024-11-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_donor_email_address',
            new_name='default_email_address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_donor_first_name',
            new_name='default_first_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_donor_last_name',
            new_name='default_last_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_donor_postcode',
            new_name='default_postcode',
        ),
    ]
