# Generated by Django 5.1.1 on 2024-10-15 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0005_alter_cat_age_if_known'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donor_first_name', models.CharField(max_length=100)),
                ('donor_last_name', models.CharField(max_length=100)),
                ('donor_email_address', models.EmailField(max_length=100)),
                ('donor_address_line1', models.CharField(blank=True, max_length=100)),
                ('donor_address_line2', models.CharField(blank=True, max_length=100)),
                ('donor_city_or_town', models.CharField(blank=True, max_length=100)),
                ('donor_county', models.CharField(blank=True, max_length=50)),
                ('donor_postcode', models.CharField(blank=True, max_length=15)),
                ('donor_country', models.CharField(blank=True, max_length=50)),
                ('donor_comment', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cats.cat')),
            ],
        ),
    ]
