# Generated by Django 5.1.1 on 2024-10-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_custom_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donation_total',
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_number',
            field=models.CharField(default=0, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
