# Generated by Django 5.1.1 on 2024-10-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_remove_donation_donation_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_telephone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
