# Generated by Django 5.1.3 on 2024-11-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_donor_telephone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donor_address_line1',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_address_line2',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_city_or_town',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_comment',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_country',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_county',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor_telephone_number',
        ),
    ]
