# Generated by Django 5.1.3 on 2024-11-11 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_alter_cat_age_if_known'),
        ('donations', '0005_remove_donation_donor_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cats.cat'),
        ),
    ]
