# Generated by Django 5.1.3 on 2024-11-11 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_alter_donation_cat'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='profiles.userprofile'),
        ),
    ]
