# Generated by Django 5.1.3 on 2024-11-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_donation_stripe_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donation_number',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
