# Generated by Django 4.2 on 2024-12-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_alter_donation_donation_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='original_donation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='donation',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
