# Generated by Django 4.2 on 2024-12-17 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_donation_original_donation_alter_donation_stripe_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='custom_amount',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='original_donation',
        ),
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True, help_text='Optionally, add a message to send to the rescue centre with your donation.'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
