# Generated by Django 5.1.1 on 2024-10-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cat_image_url_alter_cat_id_alter_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
