# Generated by Django 5.1.1 on 2024-10-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_cat_age_if_known_alter_cat_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age_if_known',
            field=models.CharField(max_length=10),
        ),
    ]
